[core]
computerName=DESKTOP-74DM2T1
coreMode=2
lastVersion=1.26.0.0
enableCrypto=false

[server]
configFile=C:/Users/user/.gemini/antigravity-ide/scratch/cross_node_agent/config/deskflow_server.conf
interface=192.168.137.1
port=24800
enableCrypto=false
cryptoEnabled=false

[security]
enableCrypto=false
requireCrypto=false

[gui]
enableUpdateCheck=false
logExpanded=true
startCoreWithGui=true

[internalConfig]
clipboardSharing=true
defaultLockToScreenState=false
disableLockToScreen=false
hasHeartbeat=true
heartbeat=5000
hotkeys\size=0
protocol=1
relativeMouseMoves=false
win32KeepForeground=false
enableCrypto=false
cryptoEnabled=false
