section: screens
	DESKTOP-74DM2T1:
	ghost:
end

section: aliases
	DESKTOP-74DM2T1:
		192.168.137.1
	ghost:
		192.168.137.39
		100.98.110.86
end

section: links
	DESKTOP-74DM2T1:
		right = ghost
	ghost:
		left = DESKTOP-74DM2T1
end

section: options
	relativeMouseMoves = false
	win32KeepForeground = false
	clipboardSharing = true
	keystroke(Control+Alt+k) = switchToScreen(ghost)
	keystroke(Control+Alt+w) = switchToScreen(DESKTOP-74DM2T1)
end
